### PR TITLE
WIP Update 'introduction to live share' post

### PR DESCRIPTION
**Pull request by jmloyola**
I added the rest of the text and the images.
I'm not quite sure how the images are going to look (I wasn't able to build the site locally).

### CODE REVIEW

**Comment by jmloyola** [comment]
I will leave this PR open for a little bit. I need to figure out how to build the site locally (I'm having dependency errors) to see how it looks.
I also would like to add a meaningful description.

**Comment by reshamas** [comment]
> I will leave this PR open for a little bit. I need to figure out how to build the site locally (I'm having dependency errors) to see how it looks.
> I also would like to add a meaningful description.

@jmloyola 
I am happy to merge it in and fix any errors.  I also tried to build it locally, and ran into some errors, and thought it might be faster just to go to directly to GitHub.
I imagine there must be a GitHub actions preview available, just as there is one for netlify.

**Comment by reshamas** [comment]
@jmloyola 
I think it looks pretty good.  The last couple links at the end of the article don't render. I would put them as:
```
- [Visual Studio Code Marketplace:  Live Share](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare)
- [Documentation: Visual Studio Live Share](https://docs.microsoft.com/en-us/visualstudio/liveshare/)
```

**Comment by reshamas** [comment]
@jmloyola 
Also, feel free to change the cover image.  I picked one image, as a test.  But, if you have a specific image in mind for code share, feel free to change it.

**Comment by jmloyola** [comment]
@reshamas I was able to build the page locally :D.
In my case the problem was with the requirements, so I deleted the `Gemfile.lock` file in the root of the repository and I run `bundle install`. A new `Gemfile.lock` should be generated.
After that, I was able to run the Jekyll server using `bundle exec jekyll serve`.

**Comment by reshamas** [comment]
@jmloyola blog page looks nice! :)
https://blog.dataumbrella.org

**Comment by reshamas** [comment]
Well, ok, the contact page doesn't work, yet.

**Pull request merged**
